# Generated by Django 6.0.7 on 2026-07-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_membership_customer_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(default='-', max_length=10),
            preserve_default=False,
        ),
    ]
